packages:
  - workflow
  - model
  - ui
  - test
  - software
  - block

catalog:
  "@platforma-sdk/workflow-tengo": ^4.1.2
  "@platforma-sdk/model": ^1.29.17
  "@platforma-sdk/ui-vue": ^1.29.17
  "@platforma-sdk/tengo-builder": ^2.1.0
  "@platforma-sdk/package-builder": ^2.15.6
  "@platforma-sdk/block-tools": ^2.5.38
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.72
  
  "@platforma-sdk/test": ^1.29.20

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  "@platforma-open/milaboratories.immunomatch-assets": ^1.0.0
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
